name: stock-sentiment-analysis
channels:
  - defaults
dependencies:
  - python=3.7
  - pandas=1.1.3
  - numpy=1.19.2
  - scikit-learn=0.23.2
  - matplotlib=3.3.2
  - nltk=3.5
  - wordcloud=1.8.0
  - joblib=0.17.0
